In [2]:
import numpy as np
import pandas as pd

In [3]:
automobile = pd.read_csv("Automobile_data.csv")

In [4]:
automobile.head(2)

symboling normalized-losses         make fuel-type aspiration num-of-doors  \
0          3                 ?  alfa-romero       gas        std          two   
1          3                 ?  alfa-romero       gas        std          two   

    body-style drive-wheels engine-location  wheel-base  ...  engine-size  \
0  convertible          rwd           front        88.6  ...          130   
1  convertible          rwd           front        88.6  ...          130   

   fuel-system  bore  stroke compression-ratio horsepower  peak-rpm city-mpg  \
0         mpfi  3.47    2.68               9.0        111      5000       21   
1         mpfi  3.47    2.68               9.0        111      5000       21   

  highway-mpg  price  
0          27  13495  
1          27  16500  

[2 rows x 26 columns]

In [9]:
auto_grp = automobile.groupby("make")

In [17]:
# trignometry functions
print(np.cos(np.pi))
print(np.sqrt(36))

-1.0
6.0


In [23]:
# Matrix manipulation
matrix = np.array([[1,2,3],[3,6,7]])
print("Matrix:" ,matrix)
matrix.shape

Matrix: [[1 2 3]
 [3 6 7]]


(2, 3)

In [27]:
# create a mtrix with arrange
# reshape takes 2 args and reshapes the given matrix to that format row x col
vec = np.arange(3,21,3)
vec.reshape(3,2)

array([[ 3,  6],
       [ 9, 12],
       [15, 18]])

In [35]:
# linspace --> Return evenly spaced numbers over a specified interval.
lin_vec = np.linspace(0,5,9)
lin_vec

array([0.   , 0.625, 1.25 , 1.875, 2.5  , 3.125, 3.75 , 4.375, 5.   ])

In [36]:
lin_vec.reshape(3,3)

array([[0.   , 0.625, 1.25 ],
       [1.875, 2.5  , 3.125],
       [3.75 , 4.375, 5.   ]])

In [39]:
# Zeros & Ones matrix creation takes shape as argument
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [41]:
# create diagonal matrix -> takes a int and np will create a matrix of shape n x n with n at it's
# diagonal starting from index 0
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
# matrix operations
mat1 = np.arange(1,7)
mat2 = np.arange(5,11)
print(mat1)
print(mat2)

[1 2 3 4 5 6]
[ 5  6  7  8  9 10]


In [ ]:
# if you try to operate on not matching shapes matrix you get an error
# -> operands could not be broadcast together with shapes (3,2) (2,3)
v1 = mat1.reshape(3,2)
v2 = mat2.reshape(2,3)
v1+v2

In [50]:
v1 = mat1.reshape(3,2)
v2 = mat2.reshape(3,2)
print(v1)
print(v2)
print(v1+v2)

[[1 2]
 [3 4]
 [5 6]]
[[ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 6  8]
 [10 12]
 [14 16]]


In [48]:
v1-v2

array([[-4, -4],
       [-4, -4],
       [-4, -4]])

In [49]:
v1*v2 #not a matrix multiplication

array([[ 5, 12],
       [21, 32],
       [45, 60]])

In [54]:
# matrix multiplication -> inner dimension should be same (n?,k),(k,m?)->(n?,m?)
# k in this case 
v2 = v2.reshape(2,3)
product = np.matmul(v1,v2)
product

array([[21, 24, 27],
       [47, 54, 61],
       [73, 84, 95]])

In [56]:
# vector(np array) with multiple datatype
vec_mil = np.array(['orange','blue','green','dark','blue','orange',6,7,4])
np.unique(vec_mil)

array(['4', '6', '7', 'blue', 'dark', 'green', 'orange'], dtype='<U6')

In [58]:
# np array with random variables
# rand -> Create an array of the given shape and populate it with random samples from a uniform 
# distribution over ``[0, 1)``
rand_arr = np.random.rand(2,3)
rand_arr

array([[0.72753438, 0.01680882, 0.58458168],
       [0.43773676, 0.19495628, 0.09375732]])

In [60]:
# randn -> Return a sample (or samples) from the "standard normal" distribution.
randn_arr = np.random.randn(3,2)
randn_arr

array([[ 0.84322078,  0.5623966 ],
       [-0.60852579, -0.75645025],
       [-0.16499612, -0.93080944]])

In [64]:
# numpy for statistical tools on array
print(np.mean(rand_arr))
print(np.std(randn_arr))
print(np.min(rand_arr))
print(np.max(rand_arr))

0.34256253941500026
0.6680693361538034
0.016808818965164507
0.7275343770581034


In [73]:
# access entries in an numpy vector
rand_vec = np.random.rand(15)
rand_vec

array([0.3283401 , 0.80988612, 0.03172978, 0.31253038, 0.82964726,
       0.00990022, 0.40146714, 0.95502568, 0.49428017, 0.19259962,
       0.94757837, 0.97174421, 0.14686413, 0.30381581, 0.95987151])

In [74]:
print(rand_vec[0])
print(rand_vec[1:4])

0.3283400970286322
[0.80988612 0.03172978 0.31253038]


In [76]:
# access multiple non-consecutive entries
print(np.arange(0,15,3))
rand_vec[np.arange(0,15,3)]

[ 0  3  6  9 12]


array([0.3283401 , 0.31253038, 0.40146714, 0.19259962, 0.14686413])

In [82]:
# access matrix
rand_vec = rand_vec.reshape(5,3)
rand_vec

array([[0.3283401 , 0.80988612, 0.03172978],
       [0.31253038, 0.82964726, 0.00990022],
       [0.40146714, 0.95502568, 0.49428017],
       [0.19259962, 0.94757837, 0.97174421],
       [0.14686413, 0.30381581, 0.95987151]])

In [87]:
print(rand_vec[2][2])
print(rand_vec[2,2])

0.4942801693318001
0.4942801693318001


In [88]:
# complex access
# return 3 column
print(rand_vec[:,2])

[0.03172978 0.00990022 0.49428017 0.97174421 0.95987151]


In [92]:
# row:col
print(rand_vec[0:2,1:3])
# all in first row
print(rand_vec[:][0])
# all in first col
print(rand_vec[:,0])

[[0.80988612 0.03172978]
 [0.82964726 0.00990022]]
[0.3283401  0.80988612 0.03172978]
[0.3283401  0.31253038 0.40146714 0.19259962 0.14686413]


In [113]:
# fetch first col
print(rand_vec)
rand_vec[:][0]

[[0.3283401  0.80988612 0.03172978]
 [0.31253038 0.82964726 0.00990022]
 [0.40146714 0.95502568 0.49428017]
 [0.19259962 0.94757837 0.97174421]
 [0.14686413 0.30381581 0.95987151]]


array([0.3283401 , 0.80988612, 0.03172978])