In [1]:
import numpy as np
import pandas as pd

In [2]:
automobile = pd.read_csv("Automobile_data.csv")

In [3]:
automobile.head(2)

symboling normalized-losses         make fuel-type aspiration num-of-doors  \
0          3                 ?  alfa-romero       gas        std          two   
1          3                 ?  alfa-romero       gas        std          two   

    body-style drive-wheels engine-location  wheel-base  ...  engine-size  \
0  convertible          rwd           front        88.6  ...          130   
1  convertible          rwd           front        88.6  ...          130   

   fuel-system  bore  stroke compression-ratio horsepower  peak-rpm city-mpg  \
0         mpfi  3.47    2.68               9.0        111      5000       21   
1         mpfi  3.47    2.68               9.0        111      5000       21   

  highway-mpg  price  
0          27  13495  
1          27  16500  

[2 rows x 26 columns]

In [4]:
auto_grp = automobile.groupby("make")

In [ ]:
auto_grp.aggregate(np.sum,'mean',axis=0)

In [11]:
# trignometry functions
print(np.cos(np.pi))
print(np.sqrt(36))

-1.0
6.0


In [12]:
# Matrix manipulation
matrix = np.array([[1,2,3],[3,6,7]])
print("Matrix:" ,matrix)
matrix.shape

Matrix: [[1 2 3]
 [3 6 7]]


(2, 3)

In [13]:
# create a mtrix with arrange
# reshape takes 2 args and reshapes the given matrix to that format row x col
vec = np.arange(3,21,3)
vec.reshape(3,2)

array([[ 3,  6],
       [ 9, 12],
       [15, 18]])

In [14]:
# linspace --> Return evenly spaced numbers over a specified interval.
lin_vec = np.linspace(0,5,9)
lin_vec

array([0.   , 0.625, 1.25 , 1.875, 2.5  , 3.125, 3.75 , 4.375, 5.   ])

In [15]:
lin_vec.reshape(3,3)

array([[0.   , 0.625, 1.25 ],
       [1.875, 2.5  , 3.125],
       [3.75 , 4.375, 5.   ]])

In [16]:
# Zeros & Ones matrix creation takes shape as argument
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
# create diagonal matrix -> takes a int and np will create a matrix of shape n x n with n at it's
# diagonal starting from index 0
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
# matrix operations
mat1 = np.arange(1,7)
mat2 = np.arange(5,11)
print(mat1)
print(mat2)

[1 2 3 4 5 6]
[ 5  6  7  8  9 10]


In [ ]:
# if you try to operate on not matching shapes matrix you get an error
# -> operands could not be broadcast together with shapes (3,2) (2,3)
v1 = mat1.reshape(3,2)
v2 = mat2.reshape(2,3)
v1+v2

In [22]:
v1 = mat1.reshape(3,2)
v2 = mat2.reshape(3,2)
print(v1)
print(v2)
print(v1+v2)

[[1 2]
 [3 4]
 [5 6]]
[[ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 6  8]
 [10 12]
 [14 16]]


In [23]:
v1-v2

array([[-4, -4],
       [-4, -4],
       [-4, -4]])

In [24]:
v1*v2 #not a matrix multiplication

array([[ 5, 12],
       [21, 32],
       [45, 60]])

In [25]:
# matrix multiplication -> inner dimension should be same (n?,k),(k,m?)->(n?,m?)
# k in this case 
v2 = v2.reshape(2,3)
product = np.matmul(v1,v2)
product

array([[21, 24, 27],
       [47, 54, 61],
       [73, 84, 95]])

In [26]:
# vector(np array) with multiple datatype
vec_mil = np.array(['orange','blue','green','dark','blue','orange',6,7,4])
np.unique(vec_mil)

array(['4', '6', '7', 'blue', 'dark', 'green', 'orange'], dtype='<U6')

In [27]:
# np array with random variables
# rand -> Create an array of the given shape and populate it with random samples from a uniform 
# distribution over ``[0, 1)``
rand_arr = np.random.rand(2,3)
rand_arr

array([[0.09578904, 0.68525293, 0.59979245],
       [0.36426454, 0.45909536, 0.39216381]])

In [28]:
# randn -> Return a sample (or samples) from the "standard normal" distribution.
randn_arr = np.random.randn(3,2)
randn_arr

array([[ 1.25536436,  1.26070112],
       [ 2.36719221,  0.12126824],
       [ 0.15291927, -1.30072001]])

In [29]:
# numpy for statistical tools on array
print(np.mean(rand_arr))
print(np.std(randn_arr))
print(np.min(rand_arr))
print(np.max(rand_arr))

0.43272635473875165
1.1561295988052591
0.0957890439982465
0.6852529258645472


In [30]:
# access entries in an numpy vector
rand_vec = np.random.rand(15)
rand_vec

array([0.01679409, 0.46968189, 0.57028536, 0.39201007, 0.45091314,
       0.66140394, 0.97773425, 0.92189145, 0.34415381, 0.29165243,
       0.11877881, 0.79793435, 0.17800307, 0.88237748, 0.07973875])

In [31]:
print(rand_vec[0])
print(rand_vec[1:4])

0.01679408533100213
[0.46968189 0.57028536 0.39201007]


In [32]:
# access multiple non-consecutive entries
print(np.arange(0,15,3))
rand_vec[np.arange(0,15,3)]

[ 0  3  6  9 12]


array([0.01679409, 0.39201007, 0.97773425, 0.29165243, 0.17800307])

In [33]:
# access matrix
rand_vec = rand_vec.reshape(5,3)
rand_vec

array([[0.01679409, 0.46968189, 0.57028536],
       [0.39201007, 0.45091314, 0.66140394],
       [0.97773425, 0.92189145, 0.34415381],
       [0.29165243, 0.11877881, 0.79793435],
       [0.17800307, 0.88237748, 0.07973875]])

In [34]:
print(rand_vec[2][2])
print(rand_vec[2,2])

0.3441538120606059
0.3441538120606059


In [35]:
# complex access
# return 3 column
print(rand_vec[:,2])

[0.57028536 0.66140394 0.34415381 0.79793435 0.07973875]


In [36]:
# row:col
print(rand_vec[0:2,1:3])
# all in first row
print(rand_vec[:][0])
# all in first col
print(rand_vec[:,0])

[[0.46968189 0.57028536]
 [0.45091314 0.66140394]]
[0.01679409 0.46968189 0.57028536]
[0.01679409 0.39201007 0.97773425 0.29165243 0.17800307]


In [37]:
# fetch first col
print(rand_vec)
rand_vec[0][0]

[[0.01679409 0.46968189 0.57028536]
 [0.39201007 0.45091314 0.66140394]
 [0.97773425 0.92189145 0.34415381]
 [0.29165243 0.11877881 0.79793435]
 [0.17800307 0.88237748 0.07973875]]


0.01679408533100213

In [40]:
# change some values in array
rand_vec[3:5]=4
rand_vec

array([[0.01679409, 0.46968189, 0.57028536],
       [0.39201007, 0.45091314, 0.66140394],
       [0.97773425, 0.92189145, 0.34415381],
       [4.        , 4.        , 4.        ],
       [4.        , 4.        , 4.        ]])

In [78]:
# multiple values replacement
#rand_vec[3:5,1:2]=[1]
rand_v = np.random.rand(25)
rand_v.reshape(5,5)

array([[0.27085249, 0.63050564, 0.98864626, 0.09823498, 0.90631701],
       [0.71153975, 0.47775479, 0.86670468, 0.58315433, 0.72906404],
       [0.56078237, 0.53975792, 0.52407687, 0.7214722 , 0.65164033],
       [0.37537834, 0.2503396 , 0.36709778, 0.15984697, 0.61919401],
       [0.32274703, 0.5133387 , 0.46320233, 0.86713011, 0.84789567]])

In [90]:
rand_vec=np.random.randn(15)
rand_vec.shape
rand_vec

array([-2.2922667 ,  0.33242358, -0.18364765, -0.14258942,  0.57440837,
        1.14466769,  0.15964771, -0.90640718, -0.64355361, -1.04467587,
       -1.81478621,  0.06524434,  0.29405825,  0.22666142, -0.59188461])

In [91]:
# conditional selection of values
rand_vec>0

array([False,  True, False, False,  True,  True,  True, False, False,
       False, False,  True,  True,  True, False])

In [93]:
rand_vec[rand_vec>0]

array([0.33242358, 0.57440837, 1.14466769, 0.15964771, 0.06524434,
       0.29405825, 0.22666142])

In [95]:
# change value based on condition
rand_vec[rand_vec>0]=5
rand_vec

array([-2.2922667 ,  5.        , -0.18364765, -0.14258942,  5.        ,
        5.        ,  5.        , -0.90640718, -0.64355361, -1.04467587,
       -1.81478621,  5.        ,  5.        ,  5.        , -0.59188461])

In [96]:
# save a numpy array on disk 
# these extensions are only redable by system(python)
np.save('saved_np_array',rand_vec)

In [98]:
# save multiple np array (file_name=np_array)
np.savez('zipped_file_name',rand_Mat1=rand_vec,rand_Mat2=rand_v)

In [103]:
# save np array as text file
np.savetxt('np_arr_txt.txt',rand_vec,delimiter=",")

In [105]:
# load np array from disk
load_vec = np.load('saved_np_array.npy')
load_vec

array([-2.2922667 ,  5.        , -0.18364765, -0.14258942,  5.        ,
        5.        ,  5.        , -0.90640718, -0.64355361, -1.04467587,
       -1.81478621,  5.        ,  5.        ,  5.        , -0.59188461])

In [106]:
# multiple loads
load_zip = np.load('zipped_file_name.npz')
load_zip

In [107]:
load_zip['rand_Mat1']

array([-2.2922667 ,  5.        , -0.18364765, -0.14258942,  5.        ,
        5.        ,  5.        , -0.90640718, -0.64355361, -1.04467587,
       -1.81478621,  5.        ,  5.        ,  5.        , -0.59188461])

In [108]:
load_zip['rand_Mat2']

array([0.27085249, 0.63050564, 0.98864626, 0.09823498, 0.90631701,
       0.71153975, 0.47775479, 0.86670468, 0.58315433, 0.72906404,
       0.56078237, 0.53975792, 0.52407687, 0.7214722 , 0.65164033,
       0.37537834, 0.2503396 , 0.36709778, 0.15984697, 0.61919401,
       0.32274703, 0.5133387 , 0.46320233, 0.86713011, 0.84789567])